version: '3.8'

services:
  # Tier 1: The Database Storage Box
  db:
    image: mysql:8.0
    container_name: backend_db
    restart: always
    # This is where we save the database rules for the MySQL server
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password123
      MYSQL_DATABASE: my_app_db
    volumes:
      - mysql_storage:/var/lib/mysql  # <-- This makes the data permanent!

  # Tier 2: The Python Web App Box
  web:
    build: .
    container_name: frontend_web
    restart: always
    ports:
      - "5000:5000"
    # This is where we feed the values into Python's os.environ.get()
    environment:
      - DB_HOST=db                 # Tells Python to call the 'db' service box
      - DB_PASSWORD=my_secure_password123
      - DB_NAME=my_app_db
    depends_on:
      - db

# Define the permanent physical storage drive on the EC2 host
volumes:
  mysql_storage:

